# Site
repository: aychsi/cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hansoo Chang
title: PhD Researcher in Applied Cognitive and Brain Sciences
email: hnsoo.chang@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  aychsi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# flickr_username: jekyll
linkedin_username: hansoo-chang-948b2214a
# xing_username: jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/IMG_7975.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a PhD researcher at Drexel University using statistical and machine learning techniques to predict mental health and mortality
  outcomes in large datasets. Previously, I completed by undergraduate degree in Cognitive Science at the University of Pennsylvania with a concentration in Computation and 
  Cognition where I also used machine learning and natural language processing techniques for analyzing customer feedback on medical and consumer products. 

  My research interests lie in the predictive ability of Biological and Brain age which can be calculated using blood-based and brain imaging data. 
  I answer these questions using tools such as multilevel linear regression frameworks, neural nets, Bayesian network analysis, and natural
  language processing.

  I also have experience in providing product improvements and insights to pharmaceutical and technology leaders backed by data analytics. These insights have been used by business
  leaders at companies like Samsung, Dexcom, and Janssen Pharmaceuticals to provide safer and more efficient product and drug development.

  I am most skilled in: <mark>R</mark> and <mark>Python</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Drexel University
        caption: 2021 - Present
        sub_title: PhD in Applied Cognitive and Brain Sciences

      - layout: top-middle
        title: University of Pennsylvania
        caption: 2017 - 2021
        sub_title: BA in Cognitive Science

# PHACS/AMP
  - title: Selected Projects and Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Using Biological Age in Children with Perinatally-Acquired HIV to Predict Mental and Physical Health Outcomes
        link: github.com/Aychsi/PHACS-AMP.git
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/Aychsi/PHACS-AMP.git
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Data from the Pediatric HIV/AIDS Cohort Study (PHACS)
        description: | # this will include new lines to allow paragraphs
          Designed a new advanced statistical framework to
          forecast mental health and mortality risks for children with PHIV over time in a large electronic health records (Pediatric HIV/AIDS Cohort
          Study). Briefly, this new algorithm incorporates the starting health condition of each child to inform future health outcomes. This method
          has been shown to outperform previous methods of predicting health outcomes using Biological Age.

      # Multimorbidity
      - layout: top-middle
        title: Biological age and brain age in midlife - relationship to multimorbidity and mental health
        link: www.sciencedirect.com/science/article/abs/pii/S0197458023002117
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            url: www.sciencedirect.com/science/article/abs/pii/S0197458023002117
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Data from the Midlife in the US (MIDUS) Study
        description: | # this will include new lines to allow paragraphs
          Developed a statistical model to incorporate both blood-based and grey matter volume to calculate both Biological and Brain Age which is used to predict multimorbidity. 
          This is the first paper to examine both biological and brain age as a predictor for multimorbidity.
  
      # Delve 
      - layout: top-middle
        title: Data Analysis for Product Development at Delve Inc.
        link: github.com/Aychsi/BG-Data-Analysis.git
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/Aychsi/BG-Data-Analysis.git
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Delve Inc. (formerly Bresslergroup Inc.) is a product innovation firm specializing in consumer and medical devices
        description: | # this will include new lines to allow paragraphs
          Various projects as a Data Science Intern at Delve Inc. This includes providing data visualization and summary measures for business leaders from various industries. 
          Highlights include performing data reduction techniques and survey analysis for Samsung, usability testing for Dexcom's CGM, and Natural Language Processing of Amazon
          reviews of Batiste (Church and Dwight) dry shampoo.
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Chang, H., Taylor, A., Ferariu, Ana., & Zhang, F., (2023). Investigating Biological and Brain 
              Age in Children in the Adolescent Brain Cognitive Development (ABCD) Study. NeuroImage,
              2023-09, under review.
      - layout: top-middle
        title: Chang, H., Street, K., Ferariu, Ana., & Zhang, F., (2023). Biological Age Model using
              Weighted Intercepts Improves Multimorbidity Prediction in Children with Perinatally-
              Acquired HIV. Statistics in Medicine, 2023-09, under review.     
      - layout: top-middle
        title: Zhang, F., Chang, H., Schaefer, S. M., & Gou, J. (2022). Biological age and brain age in
                midlife - relationship to multimorbidity and mental health. Neurobiology of Aging, 2022-09, in
                press. 
        link: https://www.sciencedirect.com/science/article/abs/pii/S0197458023002117?via%3Dihub
      - layout: top-middle
        title: Niu, X., Gou, J., Chang, H., Lowe, M., & Zhang, F. (2022). Classification model with
                weighted regularization to improve the reproducibility of neuroimaging signature
                selection. Statistics in Medicine, 41(25), 5046-5060.
        link: https://onlinelibrary.wiley.com/doi/10.1002/sim.9553
      - layout: top-middle
        title: Shim, M., Kavanaugh, M., Lacson, C., Goldstein-Levitas, N., Chang, H., Zhang, F., Fisher, K., 
              Connected through Movement - A Feasibility Study of Online Mindfulness-based Dance/Movement Therapy for Older Adults with 
              Age-related Cognitive Decline during COVID-19. Aging and Mental Health, 2023-09, under review.
  - title: Presentations # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: top-middle
        title: Investigating Biological and Brain Age in Children in the Adolescent Brain Cognitive Development (ABCD) Study
        quote: >
          May 2023
        description: | # this will include new lines to allow paragraphs
           Invited 30 minute presentation at the annual Midlife in the US (MIDUS) Investigators Meeting at the University of Wisconsin, Madison
      - layout: top-middle
        title: Investigating Biological and Brain Age in Children in the Adolescent Brain Cognitive Development (ABCD) Study
        quote: >
          May 2023
        description: |
            Presented at Statistical Methods in Imaging (SMI) Conference at the University of Minnesota on May 2023
  - title: Sample Poster
    layout: text
    content: | 
      ![Poster](images/SMI_Poster.png "Poster")
         



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
