# Site
repository: aychsi/cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hansoo Chang
title: PhD Researcher
email: hnsoo.chang@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  aychsi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# flickr_username: jekyll
linkedin_username: hansoo-chang-948b2214a
# xing_username: jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/IMG_7975.jpg
about_content: | # this will include new lines to allow paragraphs
  test

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
# PHACS/AMP
  - title: Selected Projects and Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Using Biological Age in Children with Perinatally-Acquired HIV to Predict Mental and Physical Health Outcomes
        link: github.com/Aychsi/PHACS-AMP.git
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/Aychsi/PHACS-AMP.git
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Data from the Pediatric HIV/AIDS Cohort Study (PHACS)
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

      # Multimorbidity
      - layout: top-middle
        title: Biological age and brain age in midlife - relationship to multimorbidity and mental health
        link: www.sciencedirect.com/science/article/abs/pii/S0197458023002117
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            url: www.sciencedirect.com/science/article/abs/pii/S0197458023002117
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Data from the Midlife in the US (MIDUS) Study
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  
      # Delve 
      - layout: top-middle
        title: Data Analysis for Product Development at Delve Inc.
        link: github.com/Aychsi/BG-Data-Analysis.git
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            url: github.com/Aychsi/BG-Data-Analysis.git
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Delve Inc. (formerly Bresslergroup Inc.) is a product innovation firm specializing in consumer and medical devices
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Drexel University
        caption: 2021 - Present
        sub_title: PhD in Applied Cognitive and Brain Sciences

      - layout: top-middle
        title: University of Pennsylvania
        caption: 2017 - 2021
        sub_title: BA in Cognitive Science
        


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
